const { DataTypes } = require("sequelize");
const { connectionDb } = require("..");

const Category = connectionDb.define(
  "Category",
  {
    id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true,
      autoIncrementIdentity: "GENERATED BY DEFAULT AS IDENTITY",
    },
    name: {
      type: DataTypes.STRING,
      field: "nome",
    },
  },
  {
    tableName: "categoria",
    timestamps: false,
  }
);

module.exports = { Category };
