const { DataTypes, Sequelize } = require("sequelize");
const { connectionDb } = require("..");

const SubCategory = connectionDb.define(
  "SubCategory",
  {
    id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true,
      autoIncrementIdentity: "GENERATED BY DEFAULT AS IDENTITY",
    },
    name: {
      type: DataTypes.STRING,
      field: "nome",
    },
    categoryId: {
      type: Sequelize.INTEGER,
      field: "categoria_id",
    },
  },
  {
    tableName: "sub_categoria",
    timestamps: false,
  }
);

module.exports = { SubCategory };
