const { DataTypes } = require("sequelize");
const { connectionDb } = require("..");

const User = connectionDb.define(
  "User",
  {
    id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true,
      autoIncrementIdentity: "GENERATED BY DEFAULT AS IDENTITY",
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false,
      field: "nome",
    },
    email: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    password: {
      type: DataTypes.STRING,
      allowNull: false,
      field: "senha",
    },
    photoUrl: {
      type: DataTypes.STRING,
      allowNull: true,
      field: "foto_url",
    },
    college: {
      type: DataTypes.STRING,
      field: "instituicao",
    },
    admin: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
      field: "administrador",
    },
  },
  {
    tableName: "usuario",
    timestamps: false,
  }
);

module.exports = { User };
