version: '3.9'

services:
  app:
    container_name: exchange-app
    build: .
    ports:
      - 3000:3000
  database:
    container_name: exchange-database
    image: postgres:16.1-alpine
    restart: on-failure
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database_exchange
    volumes:
      - data_pg:/data/postgres
  volumes:
    data_pg: null